//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineMonitoring {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Calibration : global::System.Configuration.ApplicationSettingsBase {
        
        private static Calibration defaultInstance = ((Calibration)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Calibration())));
        
        public static Calibration Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow1_A {
            get {
                return ((double)(this["grflow1_A"]));
            }
            set {
                this["grflow1_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow1_B {
            get {
                return ((double)(this["grflow1_B"]));
            }
            set {
                this["grflow1_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow2_A {
            get {
                return ((double)(this["grflow2_A"]));
            }
            set {
                this["grflow2_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow2_B {
            get {
                return ((double)(this["grflow2_B"]));
            }
            set {
                this["grflow2_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow3_A {
            get {
                return ((double)(this["grflow3_A"]));
            }
            set {
                this["grflow3_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow3_B {
            get {
                return ((double)(this["grflow3_B"]));
            }
            set {
                this["grflow3_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow4_A {
            get {
                return ((double)(this["grflow4_A"]));
            }
            set {
                this["grflow4_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow4_B {
            get {
                return ((double)(this["grflow4_B"]));
            }
            set {
                this["grflow4_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow1_A {
            get {
                return ((double)(this["spflow1_A"]));
            }
            set {
                this["spflow1_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow1_B {
            get {
                return ((double)(this["spflow1_B"]));
            }
            set {
                this["spflow1_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow2_A {
            get {
                return ((double)(this["spflow2_A"]));
            }
            set {
                this["spflow2_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow2_B {
            get {
                return ((double)(this["spflow2_B"]));
            }
            set {
                this["spflow2_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow3_A {
            get {
                return ((double)(this["spflow3_A"]));
            }
            set {
                this["spflow3_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow3_B {
            get {
                return ((double)(this["spflow3_B"]));
            }
            set {
                this["spflow3_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow4_A {
            get {
                return ((double)(this["spflow4_A"]));
            }
            set {
                this["spflow4_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow4_B {
            get {
                return ((double)(this["spflow4_B"]));
            }
            set {
                this["spflow4_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow5_A {
            get {
                return ((double)(this["grflow5_A"]));
            }
            set {
                this["grflow5_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow5_B {
            get {
                return ((double)(this["grflow5_B"]));
            }
            set {
                this["grflow5_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow6_A {
            get {
                return ((double)(this["grflow6_A"]));
            }
            set {
                this["grflow6_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double grflow6_B {
            get {
                return ((double)(this["grflow6_B"]));
            }
            set {
                this["grflow6_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow5_A {
            get {
                return ((double)(this["spflow5_A"]));
            }
            set {
                this["spflow5_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow5_B {
            get {
                return ((double)(this["spflow5_B"]));
            }
            set {
                this["spflow5_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow6_A {
            get {
                return ((double)(this["spflow6_A"]));
            }
            set {
                this["spflow6_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double spflow6_B {
            get {
                return ((double)(this["spflow6_B"]));
            }
            set {
                this["spflow6_B"] = value;
            }
        }
    }
}
